name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v2
    - run: cargo test
    # dogfood
    - run: cargo run

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v2
    - run: cargo fmt -- --check
